services:
  mlops:
    build:
      context: .
      dockerfile: Dockerfile
    image: itmo-mlops
    container_name: itmo-mlops
    command: ["sleep", "infinity"]

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.1
    container_name: itmo-mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/tmp/mlflow
    working_dir: /tmp/mlflow
    command:
      [
        "mlflow",
        "server",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--backend-store-uri",
        "sqlite:////tmp/mlflow/mlflow.db",
        "--default-artifact-root",
        "/tmp/mlflow/artifacts",
      ]

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: itmo-dvc-remote
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ../mlops-dvc-remote:/data
    command: ["server", "/data", "--console-address", ":9001"]

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: itmo-mlops-api
    container_name: itmo-mlops-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    command: ["conda", "run", "--no-capture-output", "-n", "mlops-api", "uvicorn", "mlops.modeling.predict:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - mlops

volumes:
  mlflow_data:
